# Generated by Django 5.0.7 on 2024-07-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_author_age_remove_post_context_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='context',
        ),
    ]
